### ISSUE TITLE
F-Cron does nothing

### ISSUE THREAD

**Issue by max-k** [abuisine/docker-fcron#1]
All tasks created in you image are actually useless.

They seems runned is f-cron stdout output but, in fact, they aren't.

It seems you forgot to transmit arguments in your shell invocation in ```environ_bash.sh```.

I'll suggest a Pull Request to make it work.

**Comment by abuisine** [comment]
Thanks Max, it is a pity I released this 👎 in the first place.
I did not take your PR as I wanted to avoid the extra bash being launched.
I released 4.0.1 which solves this
